name = "TriangleIntersect"
uuid = "dcd768d6-4344-5c62-a673-42b3679449b0"
authors = ["Roland Grinis <roland.grinis@example.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

