#!/usr/bin/env julia
"""
flux_comparison.jl - Compare PUMAS (C) and DiffPumas (Julia) flux calculations

This script:
1. Runs build/example-geometry for various parameter combinations
2. Caches C results in examples/data/flux_comparison.xml
3. Runs DiffPumas for the same parameters
4. Creates an interactive 3D plot comparing the results

The plot uses zenith angle θ (angle from vertical):
- θ = 0°  → vertical (muons from directly above)
- θ = 90° → horizontal (muons from horizon)

Usage:
    julia --project=. examples/flux_comparison.jl [OPTIONS]

Options:
    --recompute          Force recomputation of C results (default: use cached)
    --samples N, -n N    Number of Monte Carlo samples per point (default: 10000)
"""

using DiffPumas
using DiffPumas.Physics: get_material_index
using DiffPumas.Loader: print_physics_summary
using DiffPumas.GaisserFlux: flux_gccly, flux_gaisser
using DiffPumas.Geometry: run_backward_mc, compute_flux
using DiffPumas: zenith_to_elevation
using DiffPumas.Pumas: load_or_create_physics
using PlotlyJS
using Printf

# Path to C executable and cache file
const PUMAS_DIR = joinpath(dirname(@__DIR__), "..", "pumas")
const C_EXECUTABLE = joinpath(PUMAS_DIR, "build", "example-geometry")
const CACHE_FILE = joinpath(@__DIR__, "data", "flux_comparison.xml")
const PHYSICS_DUMP = joinpath(@__DIR__, "data", "materials.pumas")

"""
    run_c_example(thickness, zenith, energy_min, energy_max)

Run the C example-geometry and parse the output flux.
Note: C code uses elevation, so we convert from zenith.
"""
function run_c_example(thickness::Float64, zenith::Float64, 
                       energy_min::Float64, energy_max::Float64)
    
    if !isfile(C_EXECUTABLE)
        @warn "C executable not found: $C_EXECUTABLE"
        return NaN, NaN
    end
    
    # Convert zenith to elevation for C code
    elevation = zenith_to_elevation(zenith)
    
    # Run the C executable from the PUMAS directory (so it finds materials.pumas)
    cmd = Cmd(`$C_EXECUTABLE $thickness $elevation $energy_min $energy_max`; dir=PUMAS_DIR)
    output = try
        read(cmd, String)
    catch e
        @warn "Failed to run C executable: $e"
        return NaN, NaN
    end
    
    # Parse output: "Flux : 4.92738E-03 \pm 1.16323E-04 m^{-2} s^{-1} sr^{-1}"
    m = match(r"Flux\s*:\s*([-+]?\d+\.?\d*[Ee][-+]?\d+)\s*\\pm\s*([-+]?\d+\.?\d*[Ee][-+]?\d+)", output)
    if m !== nothing
        flux = parse(Float64, m.captures[1])
        sigma = parse(Float64, m.captures[2])
        return flux, sigma
    else
        @warn "Failed to parse C output: $output"
        return NaN, NaN
    end
end

"""
    load_cached_results()

Load cached C results from XML file.
"""
function load_cached_results()
    results = Dict{Tuple{Float64,Float64}, Tuple{Float64,Float64}}()
    
    if !isfile(CACHE_FILE)
        return results
    end
    
    try
        content = read(CACHE_FILE, String)
        for m in eachmatch(r"<result thickness=\"([^\"]+)\" zenith=\"([^\"]+)\" flux=\"([^\"]+)\" sigma=\"([^\"]+)\"", content)
            thickness = parse(Float64, m.captures[1])
            zenith = parse(Float64, m.captures[2])
            flux = parse(Float64, m.captures[3])
            sigma = parse(Float64, m.captures[4])
            results[(thickness, zenith)] = (flux, sigma)
        end
    catch e
        @warn "Failed to load cache: $e"
    end
    
    return results
end

"""
    save_cached_results(results)

Save C results to XML cache file.
"""
function save_cached_results(results::Dict{Tuple{Float64,Float64}, Tuple{Float64,Float64}})
    mkpath(dirname(CACHE_FILE))
    
    open(CACHE_FILE, "w") do io
        println(io, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
        println(io, "<!-- PUMAS flux comparison cache -->")
        println(io, "<!-- Generated by flux_comparison.jl -->")
        println(io, "<!-- zenith = angle from vertical (0° = vertical, 90° = horizontal) -->")
        println(io, "<flux_comparison energy_min=\"1e-3\" energy_max=\"1e9\">")
        
        for ((thickness, zenith), (flux, sigma)) in sort(collect(results))
            println(io, "  <result thickness=\"$thickness\" zenith=\"$zenith\" flux=\"$flux\" sigma=\"$sigma\"/>")
        end
        
        println(io, "</flux_comparison>")
    end
    
    @info "Saved $(length(results)) results to $CACHE_FILE"
end

"""
    compute_c_flux_grid(thicknesses, zeniths; recompute=false)

Compute C flux values for a grid of parameters.
"""
function compute_c_flux_grid(thicknesses::Vector{Float64}, 
                              zeniths::Vector{Float64};
                              recompute::Bool = false)
    
    energy_min = 1e-3
    energy_max = 1e9
    
    # Load cached results
    cached = load_cached_results()
    
    results = Dict{Tuple{Float64,Float64}, Tuple{Float64,Float64}}()
    
    n_total = length(thicknesses) * length(zeniths)
    n_done = 0
    
    for thickness in thicknesses
        for zenith in zeniths
            key = (thickness, zenith)
            n_done += 1
            
            if !recompute && haskey(cached, key)
                results[key] = cached[key]
                @info "[$n_done/$n_total] Using cached: thickness=$thickness m, θ=$(zenith)°"
            else
                @info "[$n_done/$n_total] Running C: thickness=$thickness m, θ=$(zenith)°"
                flux, sigma = run_c_example(thickness, zenith, energy_min, energy_max)
                results[key] = (flux, sigma)
            end
        end
    end
    
    # Save updated cache
    save_cached_results(results)
    
    return results
end

"""
    compute_julia_flux_grid(physics, thicknesses, zeniths; n_samples, energy_threshold_low, straggling, scattering)

Compute Julia flux values for a grid of parameters.
Matches PUMAS C geometry.c behavior when straggling=true, scattering=true:
- Below energy_threshold_low: STRAGGLED energy loss + MIXED scattering (transverse transport ON)
- Above energy_threshold_low: MIXED energy loss + DISABLED scattering

# Arguments
- `energy_threshold_low`: Energy threshold for mode switching in GeV (default: 100.0)
- `straggling`: Enable energy straggling (default: true)
- `scattering`: Enable scattering (default: true)
"""
function compute_julia_flux_grid(physics, 
                                  thicknesses::Vector{Float64}, 
                                  zeniths::Vector{Float64};
                                  n_samples::Int = 10000,
                                  energy_threshold_low::Float64 = 100.0,
                                  straggling::Bool = true,
                                  scattering::Bool = true)
    
    energy_min = 1e-3
    energy_max = 1e9
    
    results = Dict{Tuple{Float64,Float64}, Tuple{Float64,Float64}}()
    
    n_total = length(thicknesses) * length(zeniths)
    n_done = 0
    
    for thickness in thicknesses
        for zenith in zeniths
            n_done += 1
            elevation = zenith_to_elevation(zenith)
            @info "[$n_done/$n_total] Running Julia: thickness=$thickness m, θ=$(zenith)°"
            
            # Use provided straggling and scattering settings
            # compute_flux now returns (flux, sigma) with proper variance calculation
            flux, sigma = compute_flux(physics, 2650.0, thickness, elevation, 
                               energy_min, energy_max; n_samples=n_samples,
                               straggling=straggling, scattering=scattering,
                               energy_threshold_low=energy_threshold_low)
            
            results[(thickness, zenith)] = (flux, sigma)
        end
    end
    
    return results
end

"""
    create_comparison_plot(c_results, julia_results, thicknesses, zeniths)

Create interactive 3D comparison plot.
"""
function create_comparison_plot(c_results::Dict, julia_results::Dict,
                                 thicknesses::Vector{Float64}, 
                                 zeniths::Vector{Float64})
    
    n_t = length(thicknesses)
    n_z = length(zeniths)
    
    # Create matrices for surface plots
    c_flux = zeros(n_z, n_t)
    julia_flux = zeros(n_z, n_t)
    
    for (i, zen) in enumerate(zeniths)
        for (j, thick) in enumerate(thicknesses)
            key = (thick, zen)
            c_f = get(c_results, key, (NaN, NaN))[1]
            j_f = get(julia_results, key, (NaN, NaN))[1]
            
            c_flux[i, j] = c_f > 0 ? log10(c_f) : NaN
            julia_flux[i, j] = j_f > 0 ? log10(j_f) : NaN
        end
    end
    
    # Create 3D surface plot for flux comparison
    trace_c = surface(
        x = thicknesses,
        y = zeniths,
        z = c_flux,
        name = "PUMAS (C)",
        colorscale = "Blues",
        showscale = false,
        opacity = 0.8
    )
    
    trace_julia = surface(
        x = thicknesses,
        y = zeniths,
        z = julia_flux,
        name = "DiffPumas (Julia)",
        colorscale = "Oranges",
        showscale = false,
        opacity = 0.8
    )
    
    layout_flux = Layout(
        title = "Muon Flux Comparison: PUMAS (C) vs DiffPumas (Julia)",
        scene = attr(
            xaxis = attr(title = "Rock Thickness (m)"),
            yaxis = attr(title = "Zenith Angle θ (°)"),
            zaxis = attr(title = "log₁₀(Flux) [m⁻² s⁻¹ sr⁻¹]")
        ),
        width = 900,
        height = 700
    )
    
    plot_flux = Plot([trace_c, trace_julia], layout_flux)
    
    return plot_flux
end

"""
    create_comparison_table(c_results, julia_results)

Create a formatted comparison table.
"""
function create_comparison_table(c_results::Dict, julia_results::Dict)
    println()
    println("=" ^ 85)
    println("  PUMAS (C) vs DiffPumas (Julia) Flux Comparison")
    println("=" ^ 85)
    println()
    println("| Thickness (m) | Zenith θ (°) | PUMAS (C)    | DiffPumas (Julia) | Ratio  |")
    println("|---------------|--------------|--------------|-------------------|--------|")
    
    for key in sort(collect(keys(c_results)))
        thickness, zenith = key
        c_flux, _ = c_results[key]
        j_flux, _ = get(julia_results, key, (NaN, NaN))
        
        ratio = (c_flux > 0 && j_flux > 0 && isfinite(c_flux) && isfinite(j_flux)) ? 
                j_flux / c_flux : NaN
        
        @printf("| %13.0f | %12.0f | %12.5e | %17.5e | %6.2f |\n",
                thickness, zenith, c_flux, j_flux, ratio)
    end
    
    println("=" ^ 85)
end

"""
    save_detailed_flux_table_csv(c_results, julia_results, csv_path)

Save the detailed flux comparison table to a CSV file.
Includes flux values, relative errors (σ%), and difference percentages.
"""
function save_detailed_flux_table_csv(c_results::Dict, julia_results::Dict, csv_path::String)
    mkpath(dirname(csv_path))
    
    open(csv_path, "w") do io
        # Write CSV header
        println(io, "Thickness (m),Zenith θ (°),Julia Flux (m⁻²s⁻¹sr⁻¹),Julia σ (%),C Flux (m⁻²s⁻¹sr⁻¹),C σ (%),Diff (%)")
        
        # Write data rows
        for key in sort(collect(keys(c_results)))
            thickness, zenith = key
            c_flux, c_sigma = c_results[key]
            j_flux, j_sigma = get(julia_results, key, (NaN, NaN))
            
            # Calculate relative errors in percentage
            j_sigma_pct = (j_flux > 0 && isfinite(j_flux) && isfinite(j_sigma)) ? 
                          (j_sigma / j_flux) * 100.0 : NaN
            c_sigma_pct = (c_flux > 0 && isfinite(c_flux) && isfinite(c_sigma)) ? 
                          (c_sigma / c_flux) * 100.0 : NaN
            
            # Calculate difference percentage: ((Julia - C) / C) * 100
            diff_pct = (c_flux > 0 && j_flux > 0 && isfinite(c_flux) && isfinite(j_flux)) ? 
                       ((j_flux - c_flux) / c_flux) * 100.0 : NaN
            
            # Format values for CSV
            j_flux_str = isfinite(j_flux) ? string(j_flux) : "NaN"
            j_sigma_pct_str = isfinite(j_sigma_pct) ? string(j_sigma_pct) : "NaN"
            c_flux_str = isfinite(c_flux) ? string(c_flux) : "NaN"
            c_sigma_pct_str = isfinite(c_sigma_pct) ? string(c_sigma_pct) : "NaN"
            diff_pct_str = isfinite(diff_pct) ? string(diff_pct) : "NaN"
            
            println(io, "$thickness,$zenith,$j_flux_str,$j_sigma_pct_str,$c_flux_str,$c_sigma_pct_str,$diff_pct_str")
        end
    end
    
    @info "Saved detailed flux comparison table to: $csv_path"
end

"""
    create_detailed_flux_table(c_results, julia_results)

Create a detailed table with flux values, sigma percentages, and difference percentages.
"""
function create_detailed_flux_table(c_results::Dict, julia_results::Dict)
    println()
    println("=" ^ 120)
    println("  Detailed Flux Comparison: Values, Relative Errors, and Differences")
    println("=" ^ 120)
    println()
    println("| Thick | θ  | Julia Flux    | Julia σ% | C Flux        | C σ%   | Diff %  |")
    println("| (m)   | (°)| (m⁻²s⁻¹sr⁻¹)  |          | (m⁻²s⁻¹sr⁻¹)  |        |         |")
    println("|-------|----|---------------|----------|---------------|--------|---------|")
    
    for key in sort(collect(keys(c_results)))
        thickness, zenith = key
        c_flux, c_sigma = c_results[key]
        j_flux, j_sigma = get(julia_results, key, (NaN, NaN))
        
        # Calculate relative errors in percentage
        j_sigma_pct = (j_flux > 0 && isfinite(j_flux) && isfinite(j_sigma)) ? 
                      (j_sigma / j_flux) * 100.0 : NaN
        c_sigma_pct = (c_flux > 0 && isfinite(c_flux) && isfinite(c_sigma)) ? 
                      (c_sigma / c_flux) * 100.0 : NaN
        
        # Calculate difference percentage: ((Julia - C) / C) * 100
        diff_pct = (c_flux > 0 && j_flux > 0 && isfinite(c_flux) && isfinite(j_flux)) ? 
                   ((j_flux - c_flux) / c_flux) * 100.0 : NaN
        
        # Format output
        if isfinite(j_flux) && isfinite(c_flux)
            @printf("| %5.0f | %3.0f | %13.5e | %8.2f | %13.5e | %6.2f | %7.2f |\n",
                    thickness, zenith, j_flux, j_sigma_pct, c_flux, c_sigma_pct, diff_pct)
        else
            @printf("| %5.0f | %3.0f | %13s | %8s | %13s | %6s | %7s |\n",
                    thickness, zenith, "NaN", "NaN", "NaN", "NaN", "NaN")
        end
    end
    
    println("=" ^ 120)
end

function parse_commandline()
    n_samples = 10000
    recompute = false
    reload_physics = false
    energy_threshold_low = 100.0
    output_path = nothing  # Default will be set in main()
    straggling = true
    scattering = true
    
    if "--help" in ARGS || "-h" in ARGS
        println("""
        flux_comparison.jl - Compare PUMAS (C) and DiffPumas (Julia) flux calculations
        
        Usage:
            julia --project=. examples/flux_comparison.jl [OPTIONS]
        
        Options:
            --recompute          Force recomputation of C results (default: use cached)
            --reload-physics     Force recreation of physics tables
            --samples N, -n N    Number of Monte Carlo samples per point (default: 10000)
            --threshold N        Energy threshold for mode switching in GeV (default: 100.0)
                                Below threshold: STRAGGLED + MIXED scattering
                                Above threshold: MIXED energy loss, no scattering
            --no-straggling      Disable energy straggling (default: enabled)
            --no-scattering      Disable scattering (default: enabled)
            --output PATH, -o PATH
                                Output path for 3D plot HTML file
                                (default: examples/data/flux_comparison_3d.html)
            --help, -h           Show this help message
        
        Examples:
            julia --project=. examples/flux_comparison.jl
            julia --project=. examples/flux_comparison.jl --samples 50000
            julia --project=. examples/flux_comparison.jl --threshold 50.0
            julia --project=. examples/flux_comparison.jl --output my_plot.html
            julia --project=. examples/flux_comparison.jl --recompute --reload-physics
            julia --project=. examples/flux_comparison.jl --no-scattering
            julia --project=. examples/flux_comparison.jl --no-straggling --no-scattering
        """)
        exit(0)
    end
    
    i = 1
    while i <= length(ARGS)
        arg = ARGS[i]
        if arg == "--recompute"
            recompute = true
            i += 1
        elseif arg == "--reload-physics"
            reload_physics = true
            i += 1
        elseif arg == "--samples" || arg == "-n"
            if i + 1 <= length(ARGS)
                n_samples = parse(Int, ARGS[i + 1])
                i += 2
            else
                error("--samples requires a value")
            end
        elseif arg == "--threshold"
            if i + 1 <= length(ARGS)
                energy_threshold_low = parse(Float64, ARGS[i + 1])
                i += 2
            else
                error("--threshold requires a value")
            end
        elseif arg == "--output" || arg == "-o"
            if i + 1 <= length(ARGS)
                output_path = ARGS[i + 1]
                i += 2
            else
                error("--output requires a path")
            end
        elseif arg == "--no-straggling"
            straggling = false
            i += 1
        elseif arg == "--no-scattering"
            scattering = false
            i += 1
        elseif startswith(arg, "--samples=")
            n_samples = parse(Int, split(arg, "=")[2])
            i += 1
        elseif startswith(arg, "--threshold=")
            energy_threshold_low = parse(Float64, split(arg, "=")[2])
            i += 1
        elseif startswith(arg, "--output=")
            output_path = split(arg, "=", limit=2)[2]
            i += 1
        else
            error("Unknown argument: $arg (use --help for usage)")
        end
    end
    
    return n_samples, recompute, reload_physics, energy_threshold_low, output_path, straggling, scattering
end

function main()
    # Parse command line
    n_samples, recompute, reload_physics, energy_threshold_low, output_path, straggling, scattering = parse_commandline()
    
    # Set default output path if not provided
    if output_path === nothing
        output_path = joinpath(@__DIR__, "data", "flux_comparison.html")
    end
    
    println("=" ^ 60)
    println(" DiffPumas Flux Comparison - C vs Julia")
    println("=" ^ 60)
    println()
    
    if recompute
        println("Mode: Recompute all C results")
    else
        println("Mode: Use cached C results where available")
    end
    if reload_physics
        println("Mode: Force reload physics tables")
    end
    println("Monte Carlo samples: $n_samples")
    println("Energy threshold: $energy_threshold_low GeV")
    if straggling && scattering
        println("  Below threshold: STRAGGLED + MIXED scattering")
        println("  Above threshold: MIXED energy loss, no scattering")
    elseif straggling && !scattering
        println("  Below threshold: STRAGGLED (no scattering)")
        println("  Above threshold: MIXED energy loss, no scattering")
    elseif !straggling && scattering
        println("  Below threshold: CSDA + MIXED scattering")
        println("  Above threshold: MIXED energy loss, no scattering")
    else
        println("  All energies: Pure CSDA (no straggling, no scattering)")
    end
    println("Straggling: $straggling")
    println("Scattering: $scattering")
    println("Output plot: $output_path")
    println()
    
    # Check for C executable
    if !isfile(C_EXECUTABLE)
        println("WARNING: C executable not found at: $C_EXECUTABLE")
        println("Please compile PUMAS first:")
        println("  cd $(PUMAS_DIR) && mkdir -p build && cd build && cmake .. -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DPUMAS_BUILD_EXAMPLES=true && cmake --build .")
        println()
    end
    
    # Load or create physics (scattering tables computed from first principles)
    println("Loading physics tables...")
    if reload_physics && isfile(PHYSICS_DUMP)
        @info "Removing existing physics dump for reload..."
        rm(PHYSICS_DUMP)
    end
    physics = isfile(PHYSICS_DUMP) ? load_physics(PHYSICS_DUMP) : nothing
    if physics === nothing
        isfile(PHYSICS_DUMP) && rm(PHYSICS_DUMP; force=true)
        @info "Creating new physics tables..."
        physics = create_physics(MUON; n_energies=200, K_min=1e-3, K_max=1e9)
        save_physics(physics, PHYSICS_DUMP)
    end
    
    println("✓ Physics loaded")
    println()
    
    # Define parameter grid
    # Rock thickness: 0 to 800m in 50m steps
    thicknesses = collect(0.0:50.0:800.0)
    # Zenith angles: 0° (vertical) to 75° (near horizontal)
    zeniths = [0.0, 15.0, 30.0, 45.0, 60.0, 75.0]
    
    println("Parameter grid:")
    println("  Thicknesses: 0 to 800 m (step 50 m)")
    println("  Zenith angles: $(zeniths)°")
    println("  Energy: 1e-3 - 1e9 GeV")
    println("  MC samples: $n_samples")
    println()
    
    # Compute C results
    println("Computing PUMAS (C) flux values...")
    c_results = compute_c_flux_grid(thicknesses, zeniths; recompute=recompute)
    println()
    
    # Compute Julia results
    println("Computing DiffPumas (Julia) flux values...")
    julia_results = compute_julia_flux_grid(physics, thicknesses, zeniths; 
                                            n_samples=n_samples,
                                            energy_threshold_low=energy_threshold_low,
                                            straggling=straggling,
                                            scattering=scattering)
    println()
    
    # Print detailed flux table with sigma percentages and differences
    create_detailed_flux_table(c_results, julia_results)
    
    # Save detailed flux table to CSV (same directory as HTML)
    csv_path = joinpath(dirname(output_path), "flux_comparison.csv")
    save_detailed_flux_table_csv(c_results, julia_results, csv_path)
    
    # Create plot
    println()
    println("Creating interactive 3D plot...")
    plot_flux = create_comparison_plot(c_results, julia_results, 
                                       thicknesses, zeniths)
    
    # Save plot as HTML
    mkpath(dirname(output_path))
    open(output_path, "w") do io
        PlotlyJS.savefig(io, plot_flux, format="html")
    end
    @info "Saved 3D flux plot to: $output_path"
    
    # Display plot (in interactive environment)
    try
        display(plot_flux)
    catch
        # Not in interactive environment
    end
    
    println()
    println("Done!")
    println()
    println("View results:")
    println("  3D comparison: $output_path")
    println("  CSV table: $csv_path")
    println()
    
    return 0
end

if abspath(PROGRAM_FILE) == @__FILE__
    exit(main())
end
