"""
    DEDXLoader

Module for loading precise physics tables from PUMAS material files (dE/dx tables).
These files are generated by PUMAS and contain tabulated stopping power data.
"""
module DEDXLoader

using ..Constants

export DEDXData, load_dedx_file, find_dedx_file
export PUMAS_MATERIALS_PATH

# Default path to pumas-materials (relative to diffpumas.jl in devspace)
# diffpumas.jl is at devspace/diffpumas.jl, so we go up two levels to devspace, then into pumas-materials
const PUMAS_MATERIALS_PATH = let
    # @__DIR__ points to src/, go up to diffpumas.jl/, then up to devspace/, then into pumas-materials/
    p = joinpath(dirname(dirname(@__DIR__)), "pumas-materials")
    if !isdir(p)
        # Fallback: try environment variable
        get(ENV, "PUMAS_MATERIALS_PATH", p)
    else
        p
    end
end

"""
    DEDXData

Parsed stopping power data from a PUMAS dE/dx file.
All energies in GeV, stopping powers in GeV/(kg/m²), ranges in kg/m².
"""
struct DEDXData
    material_name::String
    particle_mass::Float64      # GeV/c²
    ZoA::Float64                # <Z/A>
    
    # Tabulated data (converted to SI-like units)
    kinetic_energy::Vector{Float64}    # GeV
    momentum::Vector{Float64}          # GeV/c
    ionization::Vector{Float64}        # GeV/(kg/m²) stopping power from ionization
    bremsstrahlung::Vector{Float64}    # GeV/(kg/m²) stopping power from brems
    pair_production::Vector{Float64}   # GeV/(kg/m²) stopping power from pairs
    photonuclear::Vector{Float64}      # GeV/(kg/m²) stopping power from photonuclear
    radiative_total::Vector{Float64}   # GeV/(kg/m²) total radiative loss
    stopping_power::Vector{Float64}    # GeV/(kg/m²) total dE/dx
    csda_range::Vector{Float64}        # kg/m² CSDA range
    density_effect::Vector{Float64}    # delta (density effect correction)
    beta::Vector{Float64}              # v/c
end

"""
    parse_header(lines)

Parse the header of a PUMAS dE/dx file.
Returns (material_name, particle_mass, ZoA, data_start_line).
"""
function parse_header(lines::Vector{String})
    material_name = ""
    particle_mass = 0.0
    ZoA = 0.0
    data_start = 0
    
    for (i, line) in enumerate(lines)
        stripped = strip(line)
        
        # Parse particle mass
        if occursin("Incident particle is a Muon with M =", stripped)
            # Extract mass in MeV
            m = match(r"M = ([\d.]+) MeV", stripped)
            if m !== nothing
                particle_mass = parse(Float64, m.captures[1]) * 1e-3  # Convert to GeV
            end
        end
        
        # Parse material name and Z/A
        if occursin("Index =", stripped) && occursin(":", stripped)
            m = match(r"Index = \d+: (\w+)", stripped)
            if m !== nothing
                material_name = m.captures[1]
            end
        end
        
        if occursin("<Z/A>", stripped)
            m = match(r"<Z/A> = ([\d.]+)", stripped)
            if m !== nothing
                ZoA = parse(Float64, m.captures[1])
            end
        end
        
        # Find data start (line after units line)
        if occursin("[MeV]", stripped) && occursin("[MeV/c]", stripped)
            data_start = i + 2  # Skip header and units line
            break
        end
    end
    
    return material_name, particle_mass, ZoA, data_start
end

"""
    load_dedx_file(filepath)

Load and parse a PUMAS dE/dx file.
Returns a DEDXData struct with all tables converted to consistent units.
"""
function load_dedx_file(filepath::String)
    if !isfile(filepath)
        error("DEDX file not found: $filepath")
    end
    
    lines = readlines(filepath)
    material_name, particle_mass, ZoA, data_start = parse_header(lines)
    
    if data_start == 0
        error("Could not find data section in DEDX file")
    end
    
    # Parse data lines
    n_lines = length(lines) - data_start + 1
    
    kinetic_energy = Float64[]
    momentum = Float64[]
    ionization = Float64[]
    bremsstrahlung = Float64[]
    pair_production = Float64[]
    photonuclear = Float64[]
    radiative_total = Float64[]
    stopping_power = Float64[]
    csda_range = Float64[]
    density_effect = Float64[]
    beta = Float64[]
    
    for i in data_start:length(lines)
        line = strip(lines[i])
        if isempty(line) || startswith(line, "#")
            continue
        end
        
        # Parse space-separated values
        parts = split(line)
        if length(parts) < 11
            continue
        end
        
        try
            # Column mapping (from file format):
            # T [MeV], p [MeV/c], Ionization, brems, pair, photonuc, Radloss, dE/dx, Range, delta, beta
            T = parse(Float64, parts[1]) * 1e-3  # MeV -> GeV
            p = parse(Float64, parts[2]) * 1e-3  # MeV/c -> GeV/c
            ion = parse(Float64, parts[3])        # MeV cm²/g
            brems = parse(Float64, parts[4])      # MeV cm²/g
            pair = parse(Float64, parts[5])       # MeV cm²/g
            photo = parse(Float64, parts[6])      # MeV cm²/g
            rad = parse(Float64, parts[7])        # MeV cm²/g
            dedx = parse(Float64, parts[8])       # MeV cm²/g
            rng = parse(Float64, parts[9])        # g/cm²
            delta = parse(Float64, parts[10])
            b = parse(Float64, parts[11])
            
            # Unit conversions:
            # MeV cm²/g = 1e-3 GeV * 1e4 m²/g = 1e1 GeV m²/g = 1e1 * 1e-3 GeV m²/(kg) = 1e-2 GeV/(kg/m²)
            # Wait, let's be careful:
            # dE/dx in MeV cm²/g means: energy loss per (g/cm²)
            # 1 MeV cm²/g = 1 MeV per (g/cm²) = 1e-3 GeV per (1e-3 kg / 1e-4 m²) = 1e-3 GeV per (10 kg/m²)
            # = 1e-4 GeV/(kg/m²)
            # Correction: 1 g/cm² = 1e-3 kg / 1e-4 m² = 10 kg/m²
            # So: 1 MeV cm²/g = 1e-3 GeV / (10 kg/m²) = 1e-4 GeV/(kg/m²)
            conv_dedx = 1e-4  # MeV cm²/g -> GeV/(kg/m²)
            
            # Range: g/cm² -> kg/m²
            # 1 g/cm² = 1e-3 kg / 1e-4 m² = 10 kg/m²
            conv_range = 10.0  # g/cm² -> kg/m²
            
            push!(kinetic_energy, T)
            push!(momentum, p)
            push!(ionization, ion * conv_dedx)
            push!(bremsstrahlung, brems * conv_dedx)
            push!(pair_production, pair * conv_dedx)
            push!(photonuclear, photo * conv_dedx)
            push!(radiative_total, rad * conv_dedx)
            push!(stopping_power, dedx * conv_dedx)
            push!(csda_range, rng * conv_range)
            push!(density_effect, delta)
            push!(beta, b)
        catch e
            # Skip malformed lines
            continue
        end
    end
    
    return DEDXData(
        material_name, particle_mass, ZoA,
        kinetic_energy, momentum, ionization, bremsstrahlung,
        pair_production, photonuclear, radiative_total,
        stopping_power, csda_range, density_effect, beta
    )
end

"""
    find_dedx_file(material_name, particle; base_path)

Find the dE/dx file for a given material and particle type.
Returns the full path to the file.
"""
function find_dedx_file(material_name::String, particle::Symbol=:muon;
                        base_path::String=PUMAS_MATERIALS_PATH)
    # Convert material name to filename format (lowercase, underscores)
    # Handle CamelCase -> snake_case conversion
    name = material_name
    # Insert underscore before uppercase letters and lowercase
    name_parts = String[]
    current = Char[]
    for c in name
        if isuppercase(c) && !isempty(current)
            push!(name_parts, String(current))
            current = [lowercase(c)]
        else
            push!(current, lowercase(c))
        end
    end
    if !isempty(current)
        push!(name_parts, String(current))
    end
    filename = join(name_parts, "_")
    filename = replace(filename, " " => "_", "-" => "_")
    
    if !endswith(filename, ".txt")
        filename *= ".txt"
    end
    
    particle_dir = particle == :muon ? "muon" : "tau"
    filepath = joinpath(base_path, "dedx", particle_dir, filename)
    
    if !isfile(filepath)
        # Try some common aliases
        aliases = Dict(
            "standardrock" => "standard_rock",
            "standard_rock" => "standard_rock",
            "rock" => "standard_rock",
            "air" => "air",
            "water" => "water"
        )
        key = lowercase(replace(material_name, " " => "", "_" => ""))
        if haskey(aliases, key)
            filename = aliases[key] * ".txt"
            filepath = joinpath(base_path, "dedx", particle_dir, filename)
        end
    end
    
    return filepath
end

"""
    interpolate_log(x, xs, ys)

Log-linear interpolation of tabulated data.
"""
function interpolate_log(x::Float64, xs::Vector{Float64}, ys::Vector{Float64})
    n = length(xs)
    
    if x <= xs[1]
        return ys[1]
    elseif x >= xs[n]
        return ys[n]
    end
    
    # Binary search for interval
    lo, hi = 1, n
    while hi - lo > 1
        mid = (lo + hi) ÷ 2
        if xs[mid] > x
            hi = mid
        else
            lo = mid
        end
    end
    
    # Log-linear interpolation
    log_x = log(x)
    log_x1, log_x2 = log(xs[lo]), log(xs[hi])
    t = (log_x - log_x1) / (log_x2 - log_x1)
    
    return ys[lo] + t * (ys[hi] - ys[lo])
end

"""
    interpolate_log_log(x, xs, ys)

Log-log interpolation of tabulated data.
"""
function interpolate_log_log(x::Float64, xs::Vector{Float64}, ys::Vector{Float64})
    n = length(xs)
    
    if x <= xs[1]
        return ys[1]
    elseif x >= xs[n]
        return ys[n]
    end
    
    # Binary search for interval
    lo, hi = 1, n
    while hi - lo > 1
        mid = (lo + hi) ÷ 2
        if xs[mid] > x
            hi = mid
        else
            lo = mid
        end
    end
    
    # Log-log interpolation
    if ys[lo] <= 0 || ys[hi] <= 0
        # Fall back to log-linear if y has zeros
        return interpolate_log(x, xs, ys)
    end
    
    log_x = log(x)
    log_x1, log_x2 = log(xs[lo]), log(xs[hi])
    log_y1, log_y2 = log(ys[lo]), log(ys[hi])
    t = (log_x - log_x1) / (log_x2 - log_x1)
    
    return exp(log_y1 + t * (log_y2 - log_y1))
end

end # module DEDXLoader

